Feature/28726/about us
deco-sites/alphabeto pull request #12
Opened 2024-12-13 16:33 UTC by Felipe-FCampos

2024-12-13 18:01 UTC, EduardoRodriguesF requested changes

2024-12-14 14:32 UTC, gsbenevides2 requested changes

2024-12-14 14:32 UTC, gsbenevides2 commented on sections/AboutUs/AboutUs.tsx
> +        <img class="hidden tablet:flex" src={banner} alt="" />
A deco possui componentes de imagens  que são otimizados e possuem uma performance melhor. E utilize a tag <Picture> para diferenciar imagens desk de mobile. Como é feito no banner home

https://docs.deco.cx/pt/performance/medias/images 

Além disso é muito importante você colocar uma opção de texto alternativo para deficientes. O atributo alt. Nesse caso você receberia o valor via props.

2024-12-16 17:25 UTC, EduardoRodriguesF requested changes

2024-12-16 17:25 UTC, EduardoRodriguesF commented on sections/AboutUs/AboutUs.tsx
>    items: AboutUsProps[];
O nome das tipagens está bastante bagunçado. ItemsAboutUs me remeteria ao prop `items`, mas se refere ao Props geral. Enquanto isso, `AboutUsProps` não se trata diretamente do AboutUs em si, mas sim dos itens.
Sugiro mudar os nomes para:
`AboutUsProps` -> `Item`
`ItemsAboutUs` -> `Props`

2024-12-17 19:28 UTC, EduardoRodriguesF requested changes

2024-12-17 19:28 UTC, EduardoRodriguesF commented on sections/AboutUs/AboutUs.tsx
> +export interface Item {
Essa prop não precisa ser exportada, apenas a `Props`.

2024-12-26 12:39 UTC, merged