Feature/28747/footer
deco-sites/alphabeto pull request #3
Opened 2024-11-01 12:12 UTC by gsbenevides2

2024-11-04 14:59 UTC, EduardoRodriguesF requested changes

2024-11-04 14:59 UTC, EduardoRodriguesF commented on components/footer/MenusAndCardMobile.tsx
> +      hiddenIcon.classList.toggle("hidden");
Prefira usar o método de acordo, para evitar inconsistências (apesar de não serem teoricamente possíveis), assim a intenção fica mais clara.
```suggestion
      visibleIcon.classList.remove("block");
      visibleIcon.classList.add("hidden");
      
      hiddenIcon.classList.add("block");
      hiddenIcon.classList.remove("hidden");
```

2024-11-04 14:59 UTC, EduardoRodriguesF commented on components/footer/MenusAndCardMobile.tsx
> +        className="text-[13px] leading-[19.5px] font-bold text-primary"
Não reparei se você está sempre trabalhando assim, mas prefira usar `class` quando estiver trabalhando em Deco.

2024-11-04 14:59 UTC, EduardoRodriguesF commented on components/footer/Newsletter.tsx
> +const afterFormSubmit = async (formId: string) => {
Não é mais fácil passar o objeto de evento como parâmetro? Assim você não precisa fazer a busca pelo elemento toda vez.

2024-11-05 12:44 UTC, gsbenevides2 commented on components/footer/Newsletter.tsx
> +const afterFormSubmit = async (formId: string) => {
Oi Edu. fiz um teste aqui e coloquei um log para ver o que o [Objeto de Evento do HTMX](https://htmx.org/events/#htmx:beforeOnLoad) traz, e ao olhar vi que ele não traz em seu target o form;
![image](https://github.com/user-attachments/assets/0a15a8bf-c9ed-474e-9214-7f0ca6dfa88c)
Por causa disso acho melhor manter assim.

2024-11-05 13:08 UTC, gsbenevides2 commented on components/footer/MenusAndCardMobile.tsx
> +        className="text-[13px] leading-[19.5px] font-bold text-primary"
Oi Edu fiz as alterações em alguns casos a palavra class conflitou com a reservada [class](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes) que usamos para criar classes.

2024-11-06 17:44 UTC, EduardoRodriguesF approved these changes

2024-11-06 17:53 UTC, merged