Feature/28730/politicas
deco-sites/alphabeto pull request #5
Opened 2024-11-22 17:17 UTC by Felipe-FCampos

2024-11-22 18:02 UTC, EduardoRodriguesF requested changes

2024-11-22 18:02 UTC, EduardoRodriguesF commented on sections/MenuInstitucional/MenuInstitucional.tsx
> +                        supportLinks.map(({ route, label }, index) => (
Simplificar estrutura.
```suggestion
                    {supportLinks?.map(({ route, label }, index) => (
```

2024-11-22 18:02 UTC, EduardoRodriguesF commented on sections/MenuInstitucional/MenuInstitucional.tsx
> +                                : "chevron-right-institutional" }`}
Qual a diferença entre o ícone de hover e normal? Se for meramente cores ou rotação, prefira alterar por props e classes.

2024-11-22 19:21 UTC, Felipe-FCampos commented on sections/MenuInstitucional/MenuInstitucional.tsx
> +                                : "chevron-right-institutional" }`}
Era somente as cores, consegui fazer a alteração por classes

2024-11-22 19:53 UTC, gsbenevides2 commented
Opa @Felipe-FCampos dei uma olhada na sua página e tenho algumas resalvas que o @EduardoRodriguesF pode comentar se quiser:
1. Percebi que você criou das sections de menu, uma para desktop e outra para mobile. Não seria possivel ter uma section só assim fica melhor para o logista alterar os conteúdo.

2. Além disso percebi que você para fazer um layout na horizontal usou um margin left na para distanciar:
![image](https://github.com/user-attachments/assets/04ac44e9-190e-46ad-8f50-a1908a7e117a)
E posicionou o menu com absolute:
![image](https://github.com/user-attachments/assets/69bfc747-4bee-45db-8bd7-421384ed99a2)
Sugiro talvez para cenários onde você queira ter um layout horizontal criar uma section que receba sections como filhas. Isso é possivel na deco através dessa [doc](https://deco.cx/docs/en/developing-capabilities/sections/accept-a-section).

3. Por ultimo pode ver que nos prints que mandei o site está desalinhado em telas maiores:
![image](https://github.com/user-attachments/assets/12f999de-4b04-4d04-beb7-9258f874995d)

2024-11-25 14:17 UTC, Felipe-FCampos commented
@gsbenevides2 Agradeço às sugestões. Fiz a junção dos menus desktop e mobile em uma única section, vou tentar juntar tudo em um section só, utilizando essa propriedade que você disse de sections filhas.

2024-11-25 16:37 UTC, gsbenevides2 commented
Opa @Felipe-FCampos vi aqui e ficou show de bola. Vi aqui que também corrigiu os pontos que o @EduardoRodriguesF  levantou. Valeu pessoal. ❤️

2024-11-25 19:27 UTC, EduardoRodriguesF approved these changes

2024-11-26 12:32 UTC, merged