Feature/29877/nossas lojas
deco-sites/alphabeto pull request #9
Opened 2024-12-10 14:03 UTC by Felipe-FCampos

2024-12-10 14:52 UTC, EduardoRodriguesF requested changes

2024-12-10 14:52 UTC, EduardoRodriguesF commented on islands/formsNossasLojas.tsx
> +  const [IsCicked, setIsClicked] = useState<number | null>(null);
1. Mantenha a semântica das variáveis. Nomes iniciados com is... geralmente se tratam de booleanos (isClicked = está clicado?). 
2. Use camelCase para as variáveis.

```suggestion
  const [selectedIndex, setSelectedIndex] = useState<number | null>(null);
```

2024-12-10 14:52 UTC, EduardoRodriguesF commented on islands/formsNossasLojas.tsx
> +            Buscar
é essencial usar o submit para formulários.
```suggestion
            type="submit"
          >
            Buscar
```

No form:

```diff
- <form class="flex justify-between mt-[10px]" action="">
+ <form class="flex justify-between mt-[10px]" onSubmit={handleFilter}>
```

2024-12-10 14:52 UTC, EduardoRodriguesF commented on islands/formsNossasLojas.tsx
> +                      </button>
Isto não deveria ser um link para o whatsapp?

2024-12-10 14:52 UTC, EduardoRodriguesF commented on islands/formsNossasLojas.tsx
> +  const content = showFiltered ? filtered : stores
O critério não deveria ser, simplesmente:
```suggestion
  const content = filtered ?? stores 
```

Ou seja, utilize os dados filtrados, caso não haja, utilize `stores` (todos)

2024-12-10 14:52 UTC, EduardoRodriguesF commented on islands/formsNossasLojas.tsx
> +    setShowFiltered(!showFiltered);
A sugestão anterior faz com que esse estado seja inútil e deve ser removido.

2024-12-10 14:52 UTC, EduardoRodriguesF commented on islands/formsNossasLojas.tsx
> +                  key={index}
Utilize outro valor que não seja o index. Isto pode gerar inconsistências no momento que o componente renderiza novamente o conteúdo.

2024-12-10 15:48 UTC, Felipe-FCampos commented on islands/formsNossasLojas.tsx
> +  const content = showFiltered ? filtered : stores
Alterei para isso aqui:
`  const content = filtered.length === 0 ? stores : filtered `
Por algum motivo o filtered já vinha vazio e o stores não era renderizado, e se caso fizesse o contrário, o filtered não funcionava.

2024-12-11 13:57 UTC, gsbenevides2 commented on .deco/blocks/pages-Nossas%2520Lojas-998808.json
> +  "path": "/nossas-lojas",
Altere a Url para /lojas no admin deco. Para manter a consistencia com o site atual.

2024-12-11 14:01 UTC, gsbenevides2 approved these changes

2024-12-13 14:11 UTC, gsbenevides2 commented
@Felipe-FCampos @EduardoRodriguesF Verifiquei aqui. E as alterações solicitadas foram feitas. Fiz o merge para resolver os conflitos e vou mergear com a main e finalizar esse PR, para não ficarmos com isso parado aqui. @Felipe-FCampos reforço novamente a necessidade de ficar de olho nos PRs.

2024-12-13 14:11 UTC, merged